# Numpy

### Importing and using numpy

In [1]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


### Creating a 2d Array

In [ ]:
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2d*2) # Can even perform operations on each element. Is treated as a matrix

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


### Conversion and dtype of array

In [13]:
print(np.array([1,1.5,"hello"]))    
# Follows a higherarchy and converts everything to the most complex for eg. if str present everything is str. If float is highest then everything is float
print(np.array([100,200.5,"300"], dtype=int))
# Dtype allows for conversion of all the elements to that type
print(np.array([100,200.5,"300"], dtype="U32"))
# To convert to string pass 'U32' to dtype

['1' '1.5' 'hello']
[100 200 300]
['100' '200.5' '300']


### Question:
- Write a python program to perform addition of 2 3x3 matrices
- Then take user definied input

In [7]:
def inp_arr(m,n):
    l=[]
    for i in range(m):
        temp=[]
        for j in range(n):
            inp=int(input(f"Enter element [{i}][{j}]: "))
            temp.append(inp)
        l.append(temp)
    arr=np.array(l,dtype=int)
    return arr


arr1=inp_arr(3,3)
arr2=inp_arr(3,3)

print(arr1+arr2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Attributes of NumPy Array
- `arr.ndim` - gives you the number of dimensions in an array
- `arr.shape` - gives you a tuple containing the order
- `arr.size` - gives you the total number of elements in an array
- `arr.dtype` - Gives datatype of the array
- `arr.itemsize` - Gives memory allocated to each element


### Creating an array with a range
Can use the `numpy.arange()` function

In [6]:
arr=np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

### Indexing and Slicing
Create a numpy array for the marks

In [5]:
l=[[78,67,56],[76,75,47],[84,59,60],[67,72,54]]

marks=np.array(l)
print(marks)

[[78 67 56]
 [76 75 47]
 [84 59 60]
 [67 72 54]]


### Sum of arrays
`np.sum()` can be used to get sum of all elements
you can also specific axis = 0 or 1 in order to get column wise or row wise respectively

### Slicing
- Create an array of 9 numbers

In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:3,1])

[2 5 8]


In [8]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(arr[arr%2==0])

[ 2  4  4  6  8  8 10]
