# Numpy

### Importing and using numpy

In [2]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


### Creating a 2d Array

In [ ]:
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2d*2) # Can even perform operations on each element. Is treated as a matrix

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


### Conversion and dtype of array

In [13]:
print(np.array([1,1.5,"hello"]))    
# Follows a higherarchy and converts everything to the most complex for eg. if str present everything is str. If float is highest then everything is float
print(np.array([100,200.5,"300"], dtype=int))
# Dtype allows for conversion of all the elements to that type
print(np.array([100,200.5,"300"], dtype="U32"))
# To convert to string pass 'U32' to dtype

['1' '1.5' 'hello']
[100 200 300]
['100' '200.5' '300']


### Question:
- Write a python program to perform addition of 2 3x3 matrices
- Then take user definied input

In [ ]:
def inp_arr(m,n):
    for i in range(m)


arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[2,3,4],[5,6,7],[8,9,0]])

print(arr1+arr2)

[[ 3  5  7]
 [ 9 11 13]
 [15 17  9]]
